version: '3.8'
services:
    redpanda:
        image: vectorized/redpanda:v21.7.1
        container_name: redpanda
        entrypoint: /bin/bash -c
        command:
            - |
                rpk config set redpanda.default_topic_partitions 8
                rpk config set redpanda.enable_idempotence true
                rpk redpanda start \
                    --smp=2 --memory=4G --overprovisioned --reserve-memory=0M --check=false \
                    --default-log-level=info --node-id=0 \
                    --kafka-addr PLAINTEXT://0.0.0.0:29092,DOCKER://redpanda:9092,OUTSIDE://redpanda:9093 \
                    --advertise-kafka-addr PLAINTEXT://redpanda:29092,DOCKER://redpanda:9092,OUTSIDE://127.0.0.1:9093
        ports:
            - 9092:9092
            - 9093:9093
            - 29092:29092
        volumes:
            - /var/lib/redpanda/data
    singlestore:
        image: singlestore/cluster-in-a-box:centos-7.5.6-9e799dbf4f-3.2.11-1.11.9
        container_name: singlestore
        volumes:
            - /var/lib/memsql
            - ./schema.sql:/init.sql:ro
            - ./data:/data:ro
        ports:
            - 3306:3306
            - 8080:8080
        environment:
            - ROOT_PASSWORD=root
            - LICENSE_KEY=${SINGLESTORE_LICENSE}
            - START_AFTER_INIT=Y
    prometheus:
        image: prom/prometheus:v2.28.1
        container_name: prometheus
        volumes:
            - ./data/metrics/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana:8.0.6
        container_name: grafana
        environment:
            - GF_USERS_DEFAULT_THEME=light
            - GF_SECURITY_ADMIN_USER=root
            - GF_SECURITY_ADMIN_PASSWORD=root
            - "GF_INSTALL_PLUGINS=grafana-worldmap-panel,https://github.com/WilliamVenner/grafana-timepicker-buttons/releases/download/v4.1.1/williamvenner-timepickerbuttons-panel-4.1.1.zip;grafana-timepicker-buttons"
        volumes:
            - /var/lib/grafana
            - ./data/metrics/dashboards:/dashboards:ro
            - ./data/metrics/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/all.yaml:ro
            - ./data/metrics/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml:ro
        ports:
            - 3000:3000
    simulator:
        build:
            context: src
            target: simulator
        image: singlestore-simulator:simulator
        container_name: simulator
    api:
        build:
            context: src
            target: api
        image: singlestore-simulator:api
        container_name: api
        ports:
            - 8000:8000