{
 "title": "User Analytics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live users over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, \"$__interval\") as time,\n  count(distinct user_id) as value\nFROM events\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Live Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from events\nwhere\n  ts > date_sub($__timeTo(), interval 5 SECOND)"
    }
   ]
  },
  {
   "title": "Top 15 Leaderboard",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT path, COUNT(distinct user_id) AS \"unique users\", max(page_time_s) as \"max time on page\"\nFROM events\nWHERE ts BETWEEN FROM_UNIXTIME(1626970859) AND FROM_UNIXTIME(1626971159)\nGROUP BY 1\nORDER BY 2 DESC, 3 DESC\nLIMIT 15;"
    }
   ]
  }
 ]
}